meta:
  url: 
slide:
  ui:
    sidebar: true
    vertical: false
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: tomorrow # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
