meta:
  url: https://fiplo.github.io/
slide:
  ui:
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: tommorow # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
build:
  useCache: false
